name: Deploy to Railway

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd Chatbot-backend
          npm install --package-lock-only
          npm ci
      
      - name: Deploy to Railway
        uses: railway/railway-action@v1
        with:
          service: chatbot-backend
          detach: true
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 