name: Railway Deployment

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Railway service name to deploy'
        required: true
        default: 'Chatbot-backend'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Deploy to Railway
        uses: bervProject/railway-deploy@main
        with:
