name: Railway Deployment

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Railway service name to deploy'
        required: true
        default: 'chatbot-backend'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Deploy to Railway
        uses: bervProject/railway-deploy@main
        with:
          service: ${{ github.event.inputs.service }}
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          detach: true

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Login to Railway
        run: echo "${RAILWAY_TOKEN}" | railway login
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: List Available Railway Services
        run: railway project
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 